@startuml "usecase(e-commerce website for tech)"


actor "Registered customer" as Registered
actor "not registered customer" as NotRegistered
actor "Admin" as Admin


rectangle "e-commerce website for tech" {
  
  
  usecase "Manage own account" as UC1
  usecase "login/logout" as UC2
  usecase "Add to cart" as UC3
  usecase "remove from cart" as UC4
  usecase "Checkout" as UC5
  usecase "View products" as UC6
  usecase "Search products" as UC7
  usecase "Manage products" as UC8
  usecase "notify user" as UC9
  usecase "Manage user account" as UC10
  usecase "Block user/Change user info" as UC11
  
  ' Зв'язки <<include>> та <<extend>>
  UC1 ..> UC2 : <<include>>
  UC3 ..> UC2 : <<include>>
  UC5 ..> UC2 : <<include>>

  UC3 ..> UC8 : <<include>>
  UC5 ..> UC8 : <<include>>
  
  UC7 ..> UC6 : <<extend>>
  UC11 ..> UC10 : <<extend>>
}

' Зв'язки акторів (Клієнти) - сині
Registered --> UC1
Registered --> UC2
Registered --> UC3
Registered --> UC4
Registered --> UC5
Registered --> UC6
Registered --> UC7


' Зв'язки акторів (Адмін) - червоні
Admin --> UC2
Admin --> UC6
Admin --> UC8
Admin --> UC9
Admin --> UC10
Admin --> UC7


NotRegistered ..> Registered : <<extend>>

@enduml